repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-case-conflict
    - id: check-symlinks
    - id: destroyed-symlinks
    - id: fix-byte-order-marker
    - id: fix-encoding-pragma
      args: [--remove]
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: requirements-txt-fixer
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    - id: reorder-python-imports
      exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
      args: [--py310-plus, "--application-directories=.:src"]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
    - id: add-trailing-comma
      args: [--py36-plus]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.0
    hooks:
    - id: autopep8
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
    - id: autoflake
      args: ["--in-place", "--expand-star-imports", "--remove-all-unused-imports"]
